#!/usr/bin/env node
// Scans public/images and writes src/data/photos.ts + src/data/heroes.ts.
//
// HDR + SDR pairing:
//   When an AVIF is found, we also look for an "SDR sibling" — same base name
//   + ".sdr.webp" or ".sdr.jpg" extension. If present, that path is emitted
//   alongside so the runtime <HDRImage> can wire it up as the
//   dynamic-range: standard fallback in a <picture> element.
import { readdir, writeFile, mkdir, stat } from "node:fs/promises";
import { join, relative } from "node:path";

const ROOT = process.cwd();
const IMG_ROOT = join(ROOT, "public", "images");

const IMG_EXT = new Set([".avif", ".jpeg", ".jpg", ".png", ".webp"]);
const VID_EXT = new Set([".mp4", ".mov", ".webm"]);
// Anything other than the primary HDR format gets paired as an SDR fallback
// when it shares the same base name as a sibling AVIF.
const SDR_EXTS = [".webp", ".jpg", ".jpeg"];

async function walk(dir) {
  const out = [];
  const entries = await readdir(dir, { withFileTypes: true });
  for (const e of entries) {
    if (e.name.startsWith(".")) continue;
    const p = join(dir, e.name);
    if (e.isDirectory()) {
      out.push(...(await walk(p)));
    } else {
      out.push(p);
    }
  }
  return out;
}

function publicPath(absPath) {
  return "/" + relative(join(ROOT, "public"), absPath).replaceAll("\\", "/");
}

function ext(p) {
  const i = p.lastIndexOf(".");
  return i >= 0 ? p.slice(i).toLowerCase() : "";
}

// Look for an SDR sibling (same base name, different extension).
async function findSdrSibling(absAvif) {
  const base = absAvif.replace(/\.avif$/i, "");
  for (const ext of SDR_EXTS) {
    try {
      await stat(base + ext);
      return base + ext;
    } catch {
      /* sibling not present */
    }
  }
  return null;
}

// Build a set of every SDR file that *is* paired with an AVIF, so we can skip
// adding those WebP/JPEG files as standalone photos in the catalog.
const all = await walk(IMG_ROOT);
const sdrSiblings = new Set();
for (const abs of all) {
  if (ext(abs) !== ".avif") continue;
  const sibling = await findSdrSibling(abs);
  if (sibling) sdrSiblings.add(sibling);
}

const photos = [];
const heroes = {};
let sdrPairCount = 0;

for (const abs of all) {
  const rel = relative(IMG_ROOT, abs).replaceAll("\\", "/");
  const parts = rel.split("/");
  const e = ext(abs);
  if (!IMG_EXT.has(e) && !VID_EXT.has(e)) continue;

  // Skip any file that's been identified as an SDR sibling of an AVIF —
  // those attach to their AVIF primary, they don't get their own entry.
  if (sdrSiblings.has(abs)) continue;
  // Skip HEIC files; browser support is too narrow to ship as a primary.
  if (e === ".heic") continue;

  const isVideo = VID_EXT.has(e);
  const src = "/images/" + rel;

  let sdrSrc = null;
  if (e === ".avif") {
    const sibling = await findSdrSibling(abs);
    if (sibling) {
      sdrSrc = "/images/" + relative(IMG_ROOT, sibling).replaceAll("\\", "/");
      sdrPairCount++;
    }
  }

  if (parts[0] === "HERO Images") {
    const project = parts[1];
    heroes[project] = heroes[project] ?? [];
    heroes[project].push({ src, isVideo, name: parts.at(-1), sdrSrc });
  } else if (/^20\d\d$/.test(parts[0])) {
    const year = parts[0];
    const category = parts[1];
    const subgroup = category === "Events" ? parts[2] : null;
    photos.push({
      src,
      year,
      category,
      subgroup,
      isVideo,
      sdrSrc,
    });
  }
}

const yearOrder = (a, b) => Number(b) - Number(a);
const numericalSort = (a, b) => {
  // sort by trailing number in filename when present
  const re = /(\d+)(?=\D*$)/;
  const am = a.src.match(re);
  const bm = b.src.match(re);
  if (am && bm) return Number(am[1]) - Number(bm[1]);
  return a.src.localeCompare(b.src);
};

photos.sort(numericalSort);

const years = Array.from(new Set(photos.map((p) => p.year))).sort(yearOrder);
const categories = ["Landscapes", "Portraits", "Events"];

await mkdir(join(ROOT, "src", "data"), { recursive: true });

const photoTs = `// Generated by scripts/build-catalog.mjs. Do not edit by hand.
export type Photo = {
  src: string;
  year: string;
  category: "Landscapes" | "Portraits" | "Events";
  subgroup: string | null;
  isVideo: boolean;
  // SDR sibling file (e.g., \`name.sdr.webp\`) found next to the AVIF.
  // Null when the photographer hasn't exported an SDR fallback yet — the
  // image will silently fall back to the Vercel-optimized SDR path.
  sdrSrc: string | null;
};

export const PHOTOS: Photo[] = ${JSON.stringify(photos, null, 2)};

export const YEARS = ${JSON.stringify(years)} as const;
export const CATEGORIES = ${JSON.stringify(categories)} as const;
`;

const heroesTs = `// Generated by scripts/build-catalog.mjs. Do not edit by hand.
export type HeroAsset = {
  src: string;
  isVideo: boolean;
  name: string;
  sdrSrc: string | null;
};
export const HEROES: Record<string, HeroAsset[]> = ${JSON.stringify(heroes, null, 2)};
`;

await writeFile(join(ROOT, "src", "data", "photos.ts"), photoTs);
await writeFile(join(ROOT, "src", "data", "heroes.ts"), heroesTs);

console.log(
  `Wrote ${photos.length} photos across ${years.length} years and ${Object.keys(heroes).length} hero projects. SDR siblings paired: ${sdrPairCount}.`
);
