// Generated by scripts/build-catalog.mjs. Do not edit by hand.
export type HeroAsset = { src: string; isVideo: boolean; name: string };
export const HEROES: Record<string, HeroAsset[]> = {
  "Aggie Reseach Finder": [
    {
      "src": "/images/HERO Images/Aggie Reseach Finder/Screenshot 2026-05-21 at 11.56.27 AM.png",
      "isVideo": false,
      "name": "Screenshot 2026-05-21 at 11.56.27 AM.png"
    },
    {
      "src": "/images/HERO Images/Aggie Reseach Finder/Screenshot 2026-05-21 at 11.56.51 AM.png",
      "isVideo": false,
      "name": "Screenshot 2026-05-21 at 11.56.51 AM.png"
    },
    {
      "src": "/images/HERO Images/Aggie Reseach Finder/Screenshot 2026-05-21 at 11.59.51 AM.png",
      "isVideo": false,
      "name": "Screenshot 2026-05-21 at 11.59.51 AM.png"
    }
  ],
  "Aggies Invent": [
    {
      "src": "/images/HERO Images/Aggies Invent/1763160692555.jpeg",
      "isVideo": false,
      "name": "1763160692555.jpeg"
    },
    {
      "src": "/images/HERO Images/Aggies Invent/Operation Halo/Slide1.png",
      "isVideo": false,
      "name": "Slide1.png"
    },
    {
      "src": "/images/HERO Images/Aggies Invent/Operation Halo/Slide7.png",
      "isVideo": false,
      "name": "Slide7.png"
    }
  ],
  "Aggies in Tech": [
    {
      "src": "/images/HERO Images/Aggies in Tech/1778885604419.jpeg",
      "isVideo": false,
      "name": "1778885604419.jpeg"
    },
    {
      "src": "/images/HERO Images/Aggies in Tech/1778885604762.jpeg",
      "isVideo": false,
      "name": "1778885604762.jpeg"
    },
    {
      "src": "/images/HERO Images/Aggies in Tech/1778885605165.jpeg",
      "isVideo": false,
      "name": "1778885605165.jpeg"
    },
    {
      "src": "/images/HERO Images/Aggies in Tech/1778885605177.jpeg",
      "isVideo": false,
      "name": "1778885605177.jpeg"
    },
    {
      "src": "/images/HERO Images/Aggies in Tech/1778885605383.jpeg",
      "isVideo": false,
      "name": "1778885605383.jpeg"
    },
    {
      "src": "/images/HERO Images/Aggies in Tech/1778885608199.jpeg",
      "isVideo": false,
      "name": "1778885608199.jpeg"
    },
    {
      "src": "/images/HERO Images/Aggies in Tech/1778885608228.jpeg",
      "isVideo": false,
      "name": "1778885608228.jpeg"
    },
    {
      "src": "/images/HERO Images/Aggies in Tech/1778885608481.jpeg",
      "isVideo": false,
      "name": "1778885608481.jpeg"
    }
  ],
  "SEC Ignite": [
    {
      "src": "/images/HERO Images/SEC Ignite/1764202057842.jpeg",
      "isVideo": false,
      "name": "1764202057842.jpeg"
    },
    {
      "src": "/images/HERO Images/SEC Ignite/ModuStep Presentation/Slide1.png",
      "isVideo": false,
      "name": "Slide1.png"
    },
    {
      "src": "/images/HERO Images/SEC Ignite/ModuStep Presentation/Slide5.png",
      "isVideo": false,
      "name": "Slide5.png"
    }
  ],
  "TEXE": [
    {
      "src": "/images/HERO Images/TEXE/1755630043188.jpeg",
      "isVideo": false,
      "name": "1755630043188.jpeg"
    },
    {
      "src": "/images/HERO Images/TEXE/1759755839431.jpeg",
      "isVideo": false,
      "name": "1759755839431.jpeg"
    },
    {
      "src": "/images/HERO Images/TEXE/Library - 1 of 1.jpeg",
      "isVideo": false,
      "name": "Library - 1 of 1.jpeg"
    },
    {
      "src": "/images/HERO Images/TEXE/Untitled - 1 of 1.jpeg",
      "isVideo": false,
      "name": "Untitled - 1 of 1.jpeg"
    }
  ],
  "ThinkTank": [
    {
      "src": "/images/HERO Images/ThinkTank/iPhone 13 - 2 of 7.jpeg",
      "isVideo": false,
      "name": "iPhone 13 - 2 of 7.jpeg"
    },
    {
      "src": "/images/HERO Images/ThinkTank/iPhone 13 - 4 of 7.jpeg",
      "isVideo": false,
      "name": "iPhone 13 - 4 of 7.jpeg"
    },
    {
      "src": "/images/HERO Images/ThinkTank/iPhone 13 - 5 of 7.jpeg",
      "isVideo": false,
      "name": "iPhone 13 - 5 of 7.jpeg"
    },
    {
      "src": "/images/HERO Images/ThinkTank/iPhone 13 - 6 of 7.jpeg",
      "isVideo": false,
      "name": "iPhone 13 - 6 of 7.jpeg"
    },
    {
      "src": "/images/HERO Images/ThinkTank/iPhone 13 - 7 of 7.jpeg",
      "isVideo": false,
      "name": "iPhone 13 - 7 of 7.jpeg"
    }
  ],
  "Tube Furnace": [
    {
      "src": "/images/HERO Images/Tube Furnace/Screenshot 2026-05-21 at 12.00.55 PM.png",
      "isVideo": false,
      "name": "Screenshot 2026-05-21 at 12.00.55 PM.png"
    }
  ]
};
